---
# tasks file for lidarr :: network
- debug:
    msg:
      - "###########################"
      - "##                       ##"
      - "##   lidarr -- network   ##"
      - "##                       ##"
      - "###########################"
- name: Add Firewall File for Lidarr
  copy:
    src: lidarr.xml
    dest: /etc/firewalld/services/lidarr.xml
  notify: reload_firewalld
- name: Ensure FirewallD is Running
  systemd:
    name: firewalld
    state: started
- name: Open FirewallD Port
  firewalld:
    service: lidarr
    immediate: yes
    permanent: yes
    state: enabled
