---
# handlers file for lidarr
- name: reload_firewalld
  systemd:
    name: firewalld
    state: reloaded
- name: empty_/opt/Lidarr
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/opt/Lidarr/*"
